### ISSUE TITLE
working title: Svelte Society Day

### ISSUE THREAD

**Issue by kevmodrome** [svelte-society/online#1]
A couple of days ago @sw-yx had a brilliant idea that we should host some kind of online meetup since the corona virus apparently became a thing 👎 

To get this sorted I think that we need to solve a couple of logistical problems, the main one being that we are spread across a wide range of time zones. It seems like most people are situated between Moscow and New York. A couple of suggestions or variants that we can try:

- Full-day event. We keep a Youtube channel running for some 12 hours where speakers can sign-up and pick timeslots and we just go with it. 
- Shorter event on for example Sunday morning New York time (like 9-10 AM) where we try to make a more condense event that runs for a couple of hours. Like the first proposal we use our Youtube channel.

Personally I would probably prefer the second alternative as I think the first one runs the risk of losing a lot of steam. It's easier to hype an event that is shorter and where people do not have to wait hours between talks. It might be a bit harder to organize and find speakers, though.

Thoughts? Ideas?

**Comment by swyxio** [comment]
i dunno, i kinda want to go for the full day tho, it would be more fun :)

i wonder if we could just run an open CFP and ask people to prerecord talks, or do we prefer to keep it live? either way we can keep the chat alive in discord. altho some people also asked me about Slack or Telegram (i dont use telegram)

**Comment by orta** [comment]
Could pre-record the talks and stream them as a twitch/YouTube/mixer channel for a day?

**Comment by kevmodrome** [comment]
Pre-recording sounds like a good idea! I like it. I'll see if I can whip up a small landing page tomorrow that we can use to promote the idea in an easier-to-digest fashion. I'll make another issue for what content that should go on there.

**Comment by antony** [comment]
I feel like this is what Twitch is designed for? I've never used it (either to watch or to broadcast) so don't quote me on that. I also believe that Mixer was in some part written by the guy who wrote the svelte vscode plugin (James Birtles), so that'd be a nice connection!

Pre-recording or live is good by me.

Big fan of Telegram but since all these streaming platforms have built-in chat so maybe that's the best way to keep the chat alive?

**Comment by shershen08** [comment]
I would vote for live talks. That's more complex though.
I had experience doing a Zoom ---> Youtube live stream with multiple ppl. How that's done:
- 1 person - organiser is streaming to YT
- then other participant joins to a Zoom call 
- gets promoted to presenters and then streams to YT


what's needed is a Zoom premium account

**Comment by shershen08** [comment]
Any updates on this?

**Comment by kevmodrome** [comment]
Yep! Launching website today. Will be using a Google form to collect CFPs.

**Comment by kevmodrome** [comment]
Closing, seems like this was the name we ended up with! :D
