### ISSUE TITLE
speakers: need more speakers

### ISSUE THREAD

**Issue by kevmodrome** [svelte-society/online#3]
If you've missed it the site is now launched at https://sveltesociety.dev/. Does anyone have a plan on how to get speakers?

We currently have one submission for a lightning talk as well as one for a regular talk. In addition to this I will be doing a regular talk as well.

If any of you can commit to doing a talk it would be much appreciated!

**Comment by swyxio** [comment]
me! i can do a talk on ssg

**Comment by shershen08** [comment]
I can present my https://svelte-workshop.js.org/

**Comment by antony** [comment]
<- Auth.

**Comment by swyxio** [comment]
woop woop! https://www.youtube.com/watch?v=0rnG-OlzGSs
