### ISSUE TITLE
practical: how to record?

### ISSUE THREAD

**Issue by kevmodrome** [svelte-society/online#4]
I'm not very experienced when it comes to recording things like this. Does anyone have any information or tips on how to do this? What software do you use, etc.

@sw-yx you do online conferences at times, right? How does it usually work?

**Comment by swyxio** [comment]
well.. usually other people organize it and i just show up as a speaker haha.

i think its usually just a Zoom chat that we hit Record on. simple stuff.

If we want a more "professional" setup we can go for crowdcast.io.

**Comment by antony** [comment]
Definitely not Zoom ;)

I thought the idea was to pre-record and then just cast?

**Comment by swyxio** [comment]
i think kev might want live. i am a little torn, i dont think i have a strong opinion.

**Comment by kevmodrome** [comment]
I'm leaning towards pre-recorded. Will be easier to organize. I have a subscription for Whereby which seems pretty good, and you can record stuff straight from the application. Will need to try it out first though.

**Comment by swyxio** [comment]
ok :) we can do prerecord

**Comment by shershen08** [comment]
I'd vote for live event. 

Talking about options to record:
 - Zoom was a security nightmare but they recently improved that part, shall we reconsider?
 - [Streamyard](https://streamyard.com/) - this solution I saw being used with great success

**Comment by kevmodrome** [comment]
Closing, we ended up going with Youtube and pre-recording everything. Seemed to have worked out well!
